sudo: required
language: c
services:
  - docker
env:
  - BASE_IMAGE_ID=$DOCKER_HUB_REPO:base-centos-$TRAVIS_BRANCH
  - GO_IMAGE_ID=$DOCKER_HUB_REPO:go-centos-$TRAVIS_BRANCH
script:
  - ci/travis.sh
branches:
  only:
    - develop
    - staging
    - master
    - production
