sudo: required
language: c
services:
  - docker
env:
  - BASE_IMAGE_TAG=$DOCKER_HUB_REPO:base-centos
script:
  - ci/travis/build-docker-images.sh
  - ci/travis/login-to-dockerhub.sh
  - ci/travis/deploy-to-dockerhub.sh
branches:
  only:
    - develop
    - staging
    - master
    - production
