sudo: required
language: c
services:
  - docker
env:
  - BASE_IMAGE_TAG=$DOCKER_HUB_REPO:base-centos
script:
  - docker build -t $BASE_IMAGE_TAG os/centos/base
  - docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
  - if [[ $TRAVIS-BRANCH != 'production' ]] docker push $BASE_IMAGE_TAG:$TRAVIS_BRANCH else docker push $BASE_IMAGE_TAG fi
branches:
  only:
    - develop
    - staging
    - master
    - production
