sudo: required
services:
  - docker
env:
  - BASE_IMAGE_TAG=$DOCKER_HUB_REPO:base-centos-latest
language: generic
before_install:
  - docker build -t $BASE_IMAGE_TAG os/centos/base/Dockerfile
  - docker login -e="$DOCKER_USERNAME" -e="$DOCKER_PASSWORD"
  - docker push $BASE_IMAGE_TAG
branches:
  only:
    - develop
    - staging
    - master
    - production
