sudo: required
language: c
services:
  - docker
env:
  - BASE_IMAGE_TAG=$DOCKER_HUB_REPO:base-centos-latest
script:
  - docker build -t $BASE_IMAGE_TAG os/centos/base
  - docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
  - docker push $BASE_IMAGE_TAG
branches:
  only:
    - develop
    - staging
    - master
    - production
