# Core Information:
FROM centos:latest
MAINTAINER "Sophia Hudson" <sophia.hudson@technicallyspeaking.io>
LABEL version="0.1.0"

# Create base directories for technicallyspeaking files:
RUN mkdir -p /usr/etc/technicallyspeaking/build && \
    mkdir -p /usr/lib/technicallyspeaking//build

# Expose port for ssh connections:
EXPOSE 22

