# Core Information:
FROM centos:latest
MAINTAINER "Sophia Hudson" <sophia.hudson@technicallyspeaking.io>
LABEL version="0.1.0"

# Initialization Scripts:
COPY ./src/init/* /etc/init.d/

# Expose port for ssh connections:
EXPOSE 22

