#!/bin/bash
source .buildvars
docker tag $DOCKER_REPOSITORY:$DOCKER_IMAGE_TAG $GCLOUD_HOSTING_DOMAIN/$GCLOUD_PROJECT_NAME/$DOCKER_REPOSITORY:$DOCKER_IMAGE_TAG
gcloud docker push $GCLOUD_HOSTING_DOMAIN/$GCLOUD_PROJECT_NAME/$DOCKER_REPOSITORY:$DOCKER_IMAGE_TAG
